pages:
  stage: deploy
  script:
    - echo $CI_PROJECT_NAME
    - shopt -s extglob
    - mkdir public
    - mv !(public) public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH